### ISSUE TITLE
settings.tabs(页签显示模式)列表页面分页组件pageSize分页器下拉显示异常

### ISSUE THREAD

**Issue by magicianCoder** [kingdee/kdesign-pro#2]
当`/config/setting.ts`配置`tabs`为`true`时，列表页面的分页**Pagination**组件pageSize分页器下拉显示不可见：分析页面结构其实是生成了两个**Pagination**组件，并且分页器被生成到左边不可见的那个**Pagination**组件下面，导致正常的右边**Pagination**组件下拉看不见选项。
[基础列表Preview](https://pro.kingdee.design/preview/typical/list/basic)

**Comment by hxh2010** [comment]
问题已记录，后续会跟进处理 [kdesign issues #670](https://github.com/kingdee/kdesign/issues/670)
